// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package com.businesstier.grpc.protobuf;

public interface ResponseTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseText)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string output_text = 1;</code>
   * @return The outputText.
   */
  java.lang.String getOutputText();
  /**
   * <code>string output_text = 1;</code>
   * @return The bytes for outputText.
   */
  com.google.protobuf.ByteString
      getOutputTextBytes();
}
